spring:
  config:
    activate:
      on-profile: local
  servlet:
    multipart:
      max-file-size: 10MB # 파일 하나 당 최대 사이즈
      max-request-size: 20MB
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:mariadb://localhost:3306/ptsd?useUnicode=true&characterEncoding=utf-8
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties: # property 사용 설정
      hibernate: # hibernate property 설정
        format_sql: true
  data:
    redis:
      host: localhost
      port: 6379

OAuth2:
  google:
    url: https://accounts.google.com/o/oauth2/v2/auth
    client-id: ${GOOGLE_CLIENT_ID}
    client-secret: ${GOOGLE_CLIENT_SECRET}
    callback-url: ${GOOGLE_CALLBACK_URL}
    token-url: https://oauth2.googleapis.com/token
    userinfo-url: https://www.googleapis.com/oauth2/v1/userinfo
    scope: https://www.googleapis.com/auth/userinfo.email https://www.googleapis.com/auth/userinfo.profile
  kakao:
    url: https://kauth.kakao.com/oauth/authorize
    client-id: ${KAKAO_CLIENT_ID}
    client-secret: ${KAKAO_CLIENT_SECRET}
    callback-url: ${KAKAO_CALLBACK_URL}
    token-url: https://kauth.kakao.com/oauth/token
    userinfo-url: https://kapi.kakao.com/v2/user/me
    userprofile-url: https://kapi.kakao.com/v1/api/talk/profile
  #  naver:
  #    url : https://nid.naver.com/oauth2.0/authorize
  #    client-id : "Your Naver Application Client ID"
  #    client-secret : "Your Naver Application Client Secret"
  #    callback-url : [URL Base]/api/oauth/login/naver/redirection
  #    token-url : https://nid.naver.com/oauth2.0/token
  #    userinfo-url : https://openapi.naver.com/v1/nid/me
Token:
  secret-key: ${SECRET_KEY}

cloud:
  aws:
    credentials:
      accessKey: ${S3_ACCESS_KEY}
      secretKey: ${S3_SECRET_KEY}
    s3:
      bucket: project-ptsd-img-server
    region:
      static: ap-northeast-2
    stack:
      auto: false
---

spring:
  config:
    activate:
      on-profile: prod
  servlet:
    multipart:
      max-file-size: 10MB # 파일 하나 당 최대 사이즈
      max-request-size: 20MB
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:mariadb://${DB_IP}:${DB_PORT}/${DB_NAME}?useUnicode=true&characterEncoding=utf-8
    driver-class-name: org.mariadb.jdbc.Driver
    username: ${DB_USER}
    password: ${DB_PW}

  jpa:
    hibernate:
      ddl-auto: ${DDL_MODE}
    properties: # property 사용 설정
      hibernate: # hibernate property 설정
        format_sql: true
  data:
    redis:
      host: redis
      port: 6379
  session:
    redis:
      namespace: auth:session

#server:
#  servlet:
#    session:
#      cookie:
#        path: /
#        name: JSESSIONID
#        http-only: true
#      timeout: 3600

OAuth2:
  google:
    url: https://accounts.google.com/o/oauth2/v2/auth
    client-id: ${GOOGLE_CLIENT_ID}
    client-secret: ${GOOGLE_CLIENT_SECRET}
    callback-url: ${GOOGLE_CALLBACK_URL}
    token-url: https://oauth2.googleapis.com/token
    userinfo-url: https://www.googleapis.com/oauth2/v1/userinfo
    scope: https://www.googleapis.com/auth/userinfo.email https://www.googleapis.com/auth/userinfo.profile
  kakao:
    url: https://kauth.kakao.com/oauth/authorize
    client-id: ${KAKAO_CLIENT_ID}
    client-secret: ${KAKAO_CLIENT_SECRET}
    callback-url: ${KAKAO_CALLBACK_URL}
    token-url: https://kauth.kakao.com/oauth/token
    userinfo-url: https://kapi.kakao.com/v2/user/me
    userprofile-url: https://kapi.kakao.com/v1/api/talk/profile
  #  naver:
  #    url : https://nid.naver.com/oauth2.0/authorize
  #    client-id : "Your Naver Application Client ID"
  #    client-secret : "Your Naver Application Client Secret"
  #    callback-url : [URL Base]/api/oauth/login/naver/redirection
  #    token-url : https://nid.naver.com/oauth2.0/token
  #    userinfo-url : https://openapi.naver.com/v1/nid/me
Token:
  secret-key: ${SECRET_KEY}

cloud:
  aws:
    credentials:
      accessKey: ${S3_ACCESS_KEY}
      secretKey: ${S3_SECRET_KEY}
    s3:
      bucket: project-ptsd-img-server
    region:
      static: ap-northeast-2
    stack:
      auto: false